### ISSUE TITLE
Cache Busting

### ISSUE THREAD

**Issue by avivace** [CoderBotOrg/backend#108]
After having applied an update, the browser sometimes loads a cached version of the vue-app resources. The vue-app build *needs* to expire after a successful updates or one of this situation can happen:

- blank `index.html`, because the webpack artifacts changed names
- cached js artifacts. if the build introduced breaking or semi-breaking API changes, old routes will be called (with 500/404 responses) making some features unusable until a force refresh (CTRL+F5) happens. Things can also break if the API works but it's not supposed to handle data in a deprecated format.

I'm opening this here but it's possible we can fix this in vue-app.

some examples of cache busting
http://flask.pocoo.org/snippets/40/

**Comment by previ** [comment]
shoud be superseded by new web app (or at least I was unable to reproduce the problem).
