### ISSUE TITLE
Photos include printed text

### ISSUE THREAD

**Issue by leonardo77** [CoderBotOrg/backend#113]
Quando viene scattata una foto le scritte sovra-impresse al video entrano a far parte della foto.

**Comment by avivace** [comment]
Could be related to https://github.com/CoderBotOrg/backend/issues/112

**Comment by avivace** [comment]
Possible solutions:

1. Move the text printing client-side
2. (backend) Disable the printing before calling the record Video / capture Photo method

I think could be more suited. Any opinion on this @previ ?

**Comment by previ** [comment]
The overlay text is a picamera feature, so definitely backend.
A simple yet effective fix could be calling `cam.set_text("")` at the end of program execution, just as `bot..stop()` is called.
Only drawback is, sometime overlay text is useful to read even after the program has completed. A minor use case.
