### ISSUE TITLE
Unable to install requirements via pip3 install -r requirements_stub.txt

### ISSUE THREAD

**Issue by grandangelo** [CoderBotOrg/backend#122]
It seems that no compiled opencv binary exists for raspbian:

pi@coderbot:~/coderbot $ pip3 install -r requirements.txt --no-cache-dir
[...]
Collecting opencv-contrib-python==3.4.3.18 (from -r requirements_stub.txt (line 26))
  Could not find a version that satisfies the requirement opencv-contrib-python==3.4.3.18 (from -r requirements_stub.txt (line 26)) (from versions: )
No matching distribution found for opencv-contrib-python==3.4.3.18 (from -r requirements_stub.txt (line 26))

Am I missing something or am I supposed to compile open cv on my own?

Thanks for great project guys.

**Comment by grandangelo** [comment]
After some investigation I found that:

- I had to upgrade to Stretch from Jessie with usual Debian method
- I had to edit /etc/pip.conf adding `[global]
extra-index-url=https://www.piwheels.org/simple` as specified [here](https://www.piwheels.org/)

Now all requirements are correctly installed.

**Comment by avivace** [comment]
Thank you! This is really useful and we will add it to the documentation/wiki since it's probably something we did but forgot to document

**Comment by avivace** [comment]
Fixed. This page of the wiki should now be clearer and avoid this situation if you upgraded to Stretch from Jessie.

https://github.com/CoderBotOrg/backend/wiki/Deploy-the-Python-Application
