### ISSUE TITLE
Include program purpose/brief documentation in (example) programs

### ISSUE THREAD

**Issue by grandangelo** [CoderBotOrg/backend#124]
I suggest to add some short description to the examples shipped. It's not easy to understand what they are supposed to do only reading their name, neither is, at least for me, always clear to understand by reading the code.

I don't know if it is possible to add something like "text labels" in Blocky containing the example description, or implement something like "show a pop up when example is loaded."

Thank you guys.

**Comment by previ** [comment]
Fixed in [online docs](https://docs.coderbot.org/usermanual/programs/).
