### ISSUE TITLE
Communicate with the coderbot using python

### ISSUE THREAD

**Issue by simone-fontana** [CoderBotOrg/backend#137]
Hi, I am trying to use some Coderbots for an introductory course to robotics and python programming for high school students. I would like to control a Coderbot with a python script in the same way it is done with the blocky interface; therefore, from a computer connected to the Coderbot, instead of loading the script on the raspberry directly. Which is the best way to communicate with the backend? Which protocol is used by the currently implemented frontend?

**Comment by avivace** [comment]
Hey @simone-fontana , that's great!
CoderBot runs Blockly on the frontend and then sends the converted Python code to the backend.
The backend exposes a RESTFul API (OpenAPI schema is in [backend/v2.yaml](https://github.com/CoderBotOrg/backend/blob/develop/v2.yml)) on the `/v2` endpoint. For future reference, you can see the API documentation at `/v2/ui/index.html` (check the [backend](https://github.com/CoderBotOrg/backend) documentation).

To execute arbitrary code, you can simply POST to /exec/, putting your program payload in the body.

Inspect the network requests (browser developer tools), looking for the /exec/ call, to understand what's happening when you click "RUN" on the UI and prepare POST requests similar to the ones normally sent by the UI.

**Comment by simone-fontana** [comment]
Thanks @avivace, now it seems pretty clear to me. Thanks a lot!
