### ISSUE TITLE
Add CONTRIBUTING document

### ISSUE THREAD

**Issue by avivace** [CoderBotOrg/backend#154]
We are missing a file explaining the various repositories scope, what does what and how could one contribute, from translating to picking up issues. We also have a quite extensive Wiki explaining how to deploy locally that could be linked..

**Comment by previ** [comment]
That's correct, at least for linking existing material and, overall, providing and overview of the project and the (now many) components.

As for the "CONTRIBUTING" document, I will prepare something inspired by [this](https://github.com/atom/atom/blob/master/CONTRIBUTING.md), according to these [general guidelines](https://mozillascience.github.io/working-open-workshop/contributing/).

**Comment by previ** [comment]
WIP: https://gist.github.com/previ/dbf4cf6eea2d9d0018847093b5e682ec

**Comment by avivace** [comment]
> WIP: https://gist.github.com/previ/dbf4cf6eea2d9d0018847093b5e682ec

Looks good so far! Can you push it on branch so I can contribute?

**Comment by previ** [comment]
> > WIP: https://gist.github.com/previ/dbf4cf6eea2d9d0018847093b5e682ec
> 
> Looks good so far! Can you push it on branch so I can contribute?

Here it is (better late then never): [CONTRIBUTING.MD](https://github.com/CoderBotOrg/backend/blob/feature/contributing/CONTRIBUTING.md).

Branch `feature/contributing`.

**Comment by avivace** [comment]
> > > WIP: https://gist.github.com/previ/dbf4cf6eea2d9d0018847093b5e682ec
> > 
> > 
> > Looks good so far! Can you push it on branch so I can contribute?
> 
> Here it is (better late then never): [CONTRIBUTING.MD](https://github.com/CoderBotOrg/backend/blob/feature/contributing/CONTRIBUTING.md).
> 
> Branch `feature/contributing`.

Thanks! I also opened the PR. Just something to keep in mind: it shouldn't overlap (too much) with the deploying/development instructions.

**Comment by previ** [comment]
> Thanks! I also opened the PR. Just something to keep in mind: it shouldn't overlap (too much) with the deploying/development instructions.

You are welcome! 

A few issues, not specific to the document itself but related to overall project policies:

- The policies (CONTRIBUTING) should be the same for all repos, but replicating the file is not practical;
- Documentation (techical) is also a bit "sparse"

So it makes probably sense to create a central repo for policies and centralize there also the technical documentation.

What do you think?
