### ISSUE TITLE
wifi "client mode" should provide fallback to "master mode".

### ISSUE THREAD

**Issue by previ** [CoderBotOrg/backend#40]
Currently if (for whatever reason) the bot cannot connect to an existing wifi, the bot is not accessible unless a physical, ethernet connection is available.

**Comment by bootsa** [comment]
I've used this process (http://www.raspberryconnect.com/network/item/315-rpi3-auto-wifi-hotspot-if-no-internet) to implement this with coderbot - works perfectly!

Brilliant project, well done!

**Comment by previ** [comment]
That's a brillian solution, I will integrate it in the coderbot software (in order to be able to specify wifi's SSID and passphrase) and SD card image.
Thanks!

**Comment by previ** [comment]
Work in progress, script works and connect to the home wifi, but sometimes the bot is not reachable through wifi.

**Comment by previ** [comment]
broken in raspbian stretch
