### ISSUE TITLE
Firmata 

### ISSUE THREAD

**Issue by VictorTagayun** [CoderBotOrg/backend#99]
Would be awesome to extend to external hardware via serial Firmata.

**Comment by previ** [comment]
I understand [firmata](firmata.org) is a protocol used for communication between microcontrollers and host computers.
The request is about using Firmata as a wire protocol between the browser (web client) and the raspberry?

**Comment by VictorTagayun** [comment]
Raspberry (host) to  a device.
TO expand the capability (IOs, etc) of raspberry or even offload some tasks from Raspberry, similar to Jhonny Five.
IF you look at [letsrobot.tv](url), they have option to use serial  comm.
[https://letsrobot.readme.io/v1.1/docs/how-to-use-l298n](url)

**Comment by previ** [comment]
Oh, I see.
There is actually a stream of development dedicated to hardware, and the idea is to integrate a "slave" microcontroller chip directly on the motor board and control it via I2C or SPI, in order to expand the I/O.

But enabling external controllers, such as Arduino, is definitely interesting. We'll give it a try.

**Comment by VictorTagayun** [comment]
Jhonny Five [http://johnny-five.io/](url) is using this.
[http://johnny-five.io/platform-support/](url)
Except that it is using JS.

**Comment by previ** [comment]
The new motor controller board now include an atmega328 onboard, integrated with Raspberry via SPI protocol (not serial).
So I am going to implement a protocol on top of SPI (ideally, firmata itself if an implementation is available for this [proposal](https://github.com/firmata/protocol/blob/master/proposals/spi-proposal.md)).

**Comment by previ** [comment]
Implemented a very limited, yet effective protocol to exchange I/O between Raspberry Pi and the Atmega.
